### ISSUE TITLE
What happened to the clips tab?

### ISSUE THREAD

**Issue by ViktorNova** [falkTX/los#12]
I just realized that at some point the clips tab has disappeared, was it causing some problems? It would be **really** great to have it back! I know I can still do File > Import MIDI, but the clips tab makes re-using parts between songs sooo much faster

**Comment by falkTX** [comment]
The clips tab was not very useful for MIDI.
Using a regular file-browser/manager will do the same job, no?

**Comment by ViktorNova** [comment]
I actually found it extremely useful, and a much better workflow than importing plain MIDI files. Even though you can still do that through a file manager, it is nice to have it in the same interface, which makes it quicker to access and also more accessible and discoverable to non-'power users'. Also when importing a midi file from the file manager, there is a dialog box that pops up asking whether to replace the project or add to it, which gets in the way. Additionally, imported MIDI files go into their own new track, but in the clips tab you can quickly drag a clip onto whatever existing track you want, so it's just all around faster

The biggest thing that makes it awesome though is being able to quickly export any part to an .mpt file straight from the sequencer, and have it appear in the clip list, a user can quickly build a library of parts in LOS that they like to re-use in different songs, and it's quite slick. Another benefit is that the MIDI clips retain their original color when imported into a new project (which is critical for me when sequencing MIDI controlled lighting in LOS)

Many commercial DAWs and sequencers (like energyXT, I think Ableton too) have this feature, it would be a shame to lose the feature for good!

**Comment by ViktorNova** [comment]
If I go through your commits where it was removed, and bring a trimmed down version of the clips tab back in (with 'preview' and all audio-related things removed), would you accept a pull request to merge it back in?


(BTW I also forgot to mention another weird thing with MIDI import where two MIDI tracks get created for each track in the MIDI file, but this does not happen in OOM when dropping MIDI clips into the timeline from the Clips tab)
