### ISSUE TITLE
Various UI elements have funny/orchestral names and should be renamed to what they actually are

### ISSUE THREAD

**Issue by ViktorNova** [falkTX/los#27]
These things should be renamed to be cleaner and more intuitive. 
Here are my ideas for what to rename things to:

- [x] The Orchestra Pit  => "Sidebar" or "Side panel" in the toolbar menu. I don't think the sidebar itself actually needs to have a title on top
- [x] EPIC Views           => "Track Views"
- [x] The Composer      => doesn't need a name, as it's the top-level window and is uncloseable
- [x] Conductor             => "MIDI", "Instrument", or "MIDI Instrument"
- [x] Performer              => "Edit..", "Edit Part", or "Piano roll" in the menu when right-clicking the part. I don't think it needs a name on the window title (MusE calls this "Pianoroll" in the right-click menu, and "MusE: Part <part name>" in the window title. Qtractor says "Edit" in the right-click menu, with "part name (track number) - Qtractor" in the piano roll's window title)

@falkTX - do you have any thoughts or preference on this, or should I just go for it?

**Comment by falkTX** [comment]
ok, let's see...

Orchestra pit => Sidebar is good, although the name is a bit generic. "Orchestra pit" is too uncommon, just change to what you think it's best.

EPIC Views, yes should be track views.

Composer, right, remove the name.

Conductor would be 'Programs' maybe? With Patches renamed to programs too.
afaik it's the official MIDI name for this.

Performer should be Piano roll.
The midi item right click should show "Open clip in Piano roll" and "Open clip in List editor".

**Comment by ViktorNova** [comment]
Perfect! 
Thanks for your input, I'm on it

**Comment by ViktorNova** [comment]
Regarding Conductor, how do you feel about renaming the tab to "Program Change" to make it more obvious? 
"Program" is a pretty generic word, but maybe I'm overthinking it
"Program Change" might be too long but maybe it's good..what do you think?

**Comment by ViktorNova** [comment]
@falkTX - I'm nearly done with all this except for the 'Conductor', and something just occured to me. 
Everywhere else in the program, this function is referred to as "Instrument", which I think we should keep, since it is a universally understood term for this, and we already have the instrument editor, instrument definitions, etc. 

I propose we change "Conductor" to "Instrument", leave "Instrument" as it is, and change "Patch" to "Program" as you suggested

Does this sound good to you?

**Comment by falkTX** [comment]
yes, please go ahead. :)

**Comment by ViktorNova** [comment]
It's finally done! I know it's only cosmetic, but man, this makes LOS much easier to take seriously now =)

**Comment by ViktorNova** [comment]
Where possible, I also renamed the functions and filenames/directory names of some of these things to make them easier to find in the future. I mentioned this in the commit logs, but there are some elements I did not rename for fear of breaking something - Conductor, Patch, and I think Orchestra Pit functions retain their original names even though they have been renamed in the UI. Maybe someday we'll get around to cleaning this up, though it's only under the hood and definitely not a huge deal
