### ISSUE TITLE
adding a waveform window

### ISSUE THREAD

**Issue by Reaper10** [falkTX/los#28]
Hi I am not a programmer but am asking if the programmer could add some features I saw some in adobe audition I would like see something like them built in to the los wave edit window. Like I said I am not a programmer so I put pitches, links and some videos to explain what I am talking about.
1. a built in vu meter in to the wave edit window
2. waveform overview a built in to the wave edit window
waveform
![adobe-audition-cs-5 5](https://cloud.githubusercontent.com/assets/8137561/16464380/8ef5d51c-3dff-11e6-8000-dfeb6d38ea7f.jpg)
3. a way to have waveform view or spectrum view or both at the same time in the wave edit window
https://helpx.adobe.com/audition/using/displaying-audio-waveform-editor.html
4. markers viewable in the wave edit window
5. spilt audio at markers 
6. export files into many audio export files
https://www.youtube.com/watch?v=zsT3-Ee-F20
list of audio clean up tools built in to the wave edit window
auto heal
https://www.youtube.com/watch?v=dPkEjEu_8I4
declicker
https://www.youtube.com/watch?v=ajo40QvcfI0
noise reduction
https://www.youtube.com/watch?v=Y-_JGy6fWeY
Removing generic noises
https://www.youtube.com/watch?v=aKEQW7wOA3g 

this could help you just add Gnome Wave.
https://sourceforge.net/projects/gwc/ 
Is los going to be made for mac, windows?
If it isn't possible to do i'll close this, Let me know

**Comment by ViktorNova** [comment]
You have a lot of good ideas =)

Unfortunately this idea is a little out of context, as LOS doesn't do audio at all. 
It is a MIDI-only sequencer. That's one of the things that falkTX changed when adapting the code from OOM. As a result though, LOS is much faster and more stable with less moving parts

**Comment by trebmuh** [comment]
@Reaper10 : you should try to find people wanting to (finally) port ReZound to Qt.

**Comment by ViktorNova** [comment]
@trebmuh
That would be RAD, I used to really like ReZound back in the day

For anyone who needs a simple (but nice) wave editor on Linux with a spectrogram, I highly recommend checking out [Ocenaudio](https://www.ocenaudio.com/features). It's not open source, but free and really good, I have yet to find something nicer for quick sample editing/conversion/etc.

**Comment by Reaper10** [comment]
sorry for wasting you time just trying find a open source Adobe Audition

**Comment by ViktorNova** [comment]
No worries
It's pretty much Ardour or MusE for open source. 
Ardour is ahead of the game but their MIDI is weird (and I don't care for the UI). MusE's MIDI is great but I can't speak to how they handle audio and I find it to be quite ugly and unstable

If you want something for Linux that is professional but _not_ open source, there is [Tracktion](https://www.tracktion.com/products/t7-daw) and [Bitwig](https://www.tracktion.com/products/t7-daw)
Tracktion has often given away their Linux version for free (older versions are also free)
